"""estoque distribuicoes auditoria e relatorios

Revision ID: 56ccb6408433
Revises: a1a644ed892b
Create Date: 2026-08-30 06:42:33.129317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ccb6408433'
down_revision = 'a1a644ed892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_distribuicao',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('id_distribuicao', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_distribuicao'], ['distribuicoes.id_distribuicao'], ),
    sa.PrimaryKeyConstraint('id_documento'),
    sa.UniqueConstraint('nome_armazenado')
    )
    with op.batch_alter_table('documentos_distribuicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_distribuicao_id_distribuicao'), ['id_distribuicao'], unique=False)

    with op.batch_alter_table('distribuicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_estoque', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('resp_recebimento', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('quantidade_devolvida', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pedido_referencia', sa.String(length=100), nullable=False))
        batch_op.create_check_constraint('ck_distribuicao_quantidade', 'quantidade > 0')
        batch_op.create_check_constraint('ck_distribuicao_devolucao', 'quantidade_devolvida >= 0')
        batch_op.create_index(batch_op.f('ix_distribuicoes_id_estoque'), ['id_estoque'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribuicoes_pedido_referencia'), ['pedido_referencia'], unique=False)
        batch_op.create_foreign_key('fk_distribuicoes_estoque', 'estoques', ['id_estoque'], ['id_estoque'])

    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estoque_minimo', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('estoque_minimo', server_default=None)

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_estoque', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('justificativa', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimentacoes_id_estoque'), ['id_estoque'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_id_usuario'), ['id_usuario'], unique=False)
        batch_op.create_foreign_key('fk_movimentacoes_usuario', 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.create_foreign_key('fk_movimentacoes_estoque', 'estoques', ['id_estoque'], ['id_estoque'])
        batch_op.drop_constraint('ck_movimentacao_tipo', type_='check')
        batch_op.create_check_constraint('ck_movimentacao_tipo', "tipo_movimentacao IN ('E', 'S', 'D', 'A')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint('ck_movimentacao_tipo', type_='check')
        batch_op.create_check_constraint('ck_movimentacao_tipo', "tipo_movimentacao IN ('E', 'S', 'D')")
        batch_op.drop_constraint('fk_movimentacoes_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_movimentacoes_estoque', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movimentacoes_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_id_estoque'))
        batch_op.drop_column('justificativa')
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('id_estoque')

    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_column('estoque_minimo')

    with op.batch_alter_table('distribuicoes', schema=None) as batch_op:
        batch_op.drop_constraint('ck_distribuicao_devolucao', type_='check')
        batch_op.drop_constraint('ck_distribuicao_quantidade', type_='check')
        batch_op.drop_constraint('fk_distribuicoes_estoque', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_distribuicoes_pedido_referencia'))
        batch_op.drop_index(batch_op.f('ix_distribuicoes_id_estoque'))
        batch_op.drop_column('pedido_referencia')
        batch_op.drop_column('quantidade_devolvida')
        batch_op.drop_column('resp_recebimento')
        batch_op.drop_column('id_estoque')

    with op.batch_alter_table('documentos_distribuicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_distribuicao_id_distribuicao'))

    op.drop_table('documentos_distribuicao')
    # ### end Alembic commands ###
