"""estrutura inicial ate tarefa 50

Revision ID: a1a644ed892b
Revises: 
Create Date: 2026-08-02 20:08:03.455980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a644ed892b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabricantes',
    sa.Column('id_fabricante', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_fabricante')
    )
    with op.batch_alter_table('fabricantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fabricantes_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_fabricantes_nome'), ['nome'], unique=False)

    op.create_table('fornecedores',
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_fornecedor')
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_fornecedores_nome'), ['nome'], unique=False)

    op.create_table('unidades_destino',
    sa.Column('id_destino', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_destino')
    )
    with op.batch_alter_table('unidades_destino', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidades_destino_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_unidades_destino_nome'), ['nome'], unique=False)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=1), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("perfil IN ('A', 'F', 'G', 'U')", name='ck_usuario_perfil'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('logs_auditoria',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=False),
    sa.Column('id_entidade', sa.Integer(), nullable=True),
    sa.Column('valores_anteriores', sa.Text(), nullable=True),
    sa.Column('valores_novos', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_id_usuario'), ['id_usuario'], unique=False)

    op.create_table('medicamentos',
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('classificacao', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('uso', sa.String(length=255), nullable=False),
    sa.Column('apresentacao', sa.String(length=120), nullable=False),
    sa.Column('principio_ativo', sa.String(length=150), nullable=False),
    sa.Column('id_fabricante', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_fabricante'], ['fabricantes.id_fabricante'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_medicamento')
    )
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicamentos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicamentos_id_fabricante'), ['id_fabricante'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicamentos_id_usuario'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicamentos_nome'), ['nome'], unique=False)

    op.create_table('aquisicoes',
    sa.Column('id_aquisicao', sa.Integer(), nullable=False),
    sa.Column('dt_compra', sa.Date(), nullable=False),
    sa.Column('dt_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('vlr_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vlr_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notafiscal', sa.String(length=100), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('dt_validade', sa.Date(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='ck_aquisicao_quantidade_positiva'),
    sa.CheckConstraint('vlr_unitario >= 0', name='ck_aquisicao_valor_positivo'),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedores.id_fornecedor'], ),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamentos.id_medicamento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_aquisicao'),
    sa.UniqueConstraint('id_fornecedor', 'notafiscal', 'lote', 'id_medicamento', name='uq_aquisicao_duplicada')
    )
    with op.batch_alter_table('aquisicoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aquisicoes_dt_validade'), ['dt_validade'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquisicoes_id_fornecedor'), ['id_fornecedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquisicoes_id_medicamento'), ['id_medicamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquisicoes_id_usuario'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquisicoes_lote'), ['lote'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquisicoes_notafiscal'), ['notafiscal'], unique=False)

    op.create_table('distribuicoes',
    sa.Column('id_distribuicao', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('id_destino', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('dt_validade', sa.Date(), nullable=False),
    sa.Column('dt_distribuicao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resp_distribuicao', sa.Integer(), nullable=False),
    sa.Column('resp_liberacao', sa.Integer(), nullable=False),
    sa.Column('vlr_saida', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_destino'], ['unidades_destino.id_destino'], ),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamentos.id_medicamento'], ),
    sa.ForeignKeyConstraint(['resp_distribuicao'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['resp_liberacao'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_distribuicao')
    )
    op.create_table('documentos_aquisicao',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('id_aquisicao', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_aquisicao'], ['aquisicoes.id_aquisicao'], ),
    sa.PrimaryKeyConstraint('id_documento'),
    sa.UniqueConstraint('nome_armazenado')
    )
    with op.batch_alter_table('documentos_aquisicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_aquisicao_id_aquisicao'), ['id_aquisicao'], unique=False)

    op.create_table('estoques',
    sa.Column('id_estoque', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('id_aquisicao', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('dt_validade', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade >= 0', name='ck_estoque_nao_negativo'),
    sa.ForeignKeyConstraint(['id_aquisicao'], ['aquisicoes.id_aquisicao'], ),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamentos.id_medicamento'], ),
    sa.PrimaryKeyConstraint('id_estoque'),
    sa.UniqueConstraint('id_aquisicao', name='uq_estoque_aquisicao')
    )
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoques_dt_validade'), ['dt_validade'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoques_id_aquisicao'), ['id_aquisicao'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoques_id_medicamento'), ['id_medicamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoques_lote'), ['lote'], unique=False)

    op.create_table('movimentacoes',
    sa.Column('id_movimentacao', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=1), nullable=False),
    sa.Column('dt_movimentacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('id_aquisicao', sa.Integer(), nullable=True),
    sa.Column('id_distribuicao', sa.Integer(), nullable=True),
    sa.Column('vlr_movimentacao', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint("tipo_movimentacao IN ('E', 'S', 'D')", name='ck_movimentacao_tipo'),
    sa.CheckConstraint('quantidade > 0', name='ck_movimentacao_quantidade'),
    sa.ForeignKeyConstraint(['id_aquisicao'], ['aquisicoes.id_aquisicao'], ),
    sa.ForeignKeyConstraint(['id_distribuicao'], ['distribuicoes.id_distribuicao'], ),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamentos.id_medicamento'], ),
    sa.PrimaryKeyConstraint('id_movimentacao')
    )
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_dt_movimentacao'), ['dt_movimentacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_id_aquisicao'), ['id_aquisicao'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_id_distribuicao'), ['id_distribuicao'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_id_medicamento'), ['id_medicamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_tipo_movimentacao'), ['tipo_movimentacao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_tipo_movimentacao'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_id_medicamento'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_id_distribuicao'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_id_aquisicao'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_dt_movimentacao'))

    op.drop_table('movimentacoes')
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoques_lote'))
        batch_op.drop_index(batch_op.f('ix_estoques_id_medicamento'))
        batch_op.drop_index(batch_op.f('ix_estoques_id_aquisicao'))
        batch_op.drop_index(batch_op.f('ix_estoques_dt_validade'))

    op.drop_table('estoques')
    with op.batch_alter_table('documentos_aquisicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_aquisicao_id_aquisicao'))

    op.drop_table('documentos_aquisicao')
    op.drop_table('distribuicoes')
    with op.batch_alter_table('aquisicoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aquisicoes_notafiscal'))
        batch_op.drop_index(batch_op.f('ix_aquisicoes_lote'))
        batch_op.drop_index(batch_op.f('ix_aquisicoes_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_aquisicoes_id_medicamento'))
        batch_op.drop_index(batch_op.f('ix_aquisicoes_id_fornecedor'))
        batch_op.drop_index(batch_op.f('ix_aquisicoes_dt_validade'))

    op.drop_table('aquisicoes')
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicamentos_nome'))
        batch_op.drop_index(batch_op.f('ix_medicamentos_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_medicamentos_id_fabricante'))
        batch_op.drop_index(batch_op.f('ix_medicamentos_codigo'))

    op.drop_table('medicamentos')
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_entidade'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_acao'))

    op.drop_table('logs_auditoria')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_cpf'))

    op.drop_table('usuarios')
    with op.batch_alter_table('unidades_destino', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_destino_nome'))
        batch_op.drop_index(batch_op.f('ix_unidades_destino_cnpj'))

    op.drop_table('unidades_destino')
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_nome'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_cnpj'))

    op.drop_table('fornecedores')
    with op.batch_alter_table('fabricantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fabricantes_nome'))
        batch_op.drop_index(batch_op.f('ix_fabricantes_cnpj'))

    op.drop_table('fabricantes')
    # ### end Alembic commands ###
